name: Project Build

on: [push]

jobs:
  build-server:
    strategy:
      matrix:
        version:
          - 7.0.x
        os: 
          - ubuntu-latest
            #- windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet $DOTNET_VERSION
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.version}}
      - name: Build Game Server
        run: dotnet build Source/Server/GameServer.csproj
      - name: Build Game Client
        run: dotnet build Source/Client/GameClient.csproj
